### ISSUE TITLE
following "docker on scicomp environment" instructions does not result in docker being installed

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#281]
**Proposed Domain**
Specify where should the new content should go (Generation, Bioinformatics, Computing, Resource Libraries)

https://sciwiki.fredhutch.org/compdemos/Docker/

**Content Summary**
Summarize the topic you'd like to be expanded upon or added.  

Followed the instructions, ran this command:

```
prox new --docker --no-bootstrap --mem 10G --disk 30 jenkins-test
```

Ended up with this error which I am not sure is a real error:

```
...

Host jenkins-test is up and running, you can now connect!
e.g. "prox ssh jenkins-test" or "prox ssh root@jenkins-test"
Traceback (most recent call last):
  File "/app/bin/cmdprox.py", line 1172, in <module>
    main()
  File "/app/bin/cmdprox.py", line 676, in main
    ssh_exec('root', pwd, ['mkdir -p .ssh',], h)
  File "/app/bin/cmdprox.py", line 958, in ssh_exec
    ssh.connect(host, username=user, password=pwd)
  File "/app/easybuild/software/Python/3.6.5-foss-2016b-fh3/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/client.py", line 357, in connect
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 140.107.117.211
```

...because I *was* able to ssh to `root@jenkins-test`.

However, docker is not installed on the host:

```
root@jenkins-test:~# docker run hello-world

Command 'docker' not found, but can be installed with:

apt install docker.io
```

**Local Content Expert(s)**
Suggest any Fred Hutch based experts who we might ask to contribute.

@dirkpetersen

**Comment by dtenenba** [comment]
Just to clarify: once the box is up I can install Docker with the suggested command, but the instructions imply that the `--docker` flag will do this for you. So either there is a problem with the suggested command, or we can tell people to install Docker manually.
